"""add index on refresh_tokens expires_at

Revision ID: 451e5bff2824
Revises: 4c5bbe1e33cb
Create Date: 2026-01-26 17:19:15.868356

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "451e5bff2824"
down_revision: Union[str, Sequence[str], None] = "4c5bbe1e33cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_activities_user_id"), "activities", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_categories_user_id"), "categories", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_global_constraints_user_id"),
        "global_constraints",
        ["user_id"],
        unique=True,
    )
    op.create_index(op.f("ix_groups_user_id"), "groups", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###

    op.create_index(
        op.f("ix_refresh_tokens_expires_at"),
        "refresh_tokens",
        ["expires_at"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_tokens_expires_at"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_groups_user_id"), table_name="groups")
    op.drop_index(
        op.f("ix_global_constraints_user_id"), table_name="global_constraints"
    )
    op.drop_index(op.f("ix_categories_user_id"), table_name="categories")
    op.drop_index(op.f("ix_activities_user_id"), table_name="activities")
    # ### end Alembic commands ###
