"""add exception_dates to tasks

Revision ID: 5b37f0a8237b
Revises: 7d4558e93c61
Create Date: 2026-02-15 21:57:04.923598

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b37f0a8237b"
down_revision: str | Sequence[str] | None = "7d4558e93c61"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("exception_dates", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "exception_dates")
    # ### end Alembic commands ###
